version: '3'

dotenv: ['.env']

env:
  TITLE: Online Banking Demo
  DEFAULT_REGION: canadacentral

includes:
  local:
    taskfile: ./tasks/Taskfile.local.yml
    internal: false

  cloud:
    taskfile: ./tasks/Taskfile.cloud.yml
    internal: false

  e2e:
    taskfile: ./tasks/Taskfile.e2e.yml
    internal: false

  lint:
    taskfile: ./tasks/Taskfile.lint.yml
    internal: false