version: '3'

vars:
  DOCKER_TAG: '{{default "latest" .CLI_ARGS}}'

tasks:
  default:
    desc: Build all container images using Azure ACR
    cmds:
      - task: user-service
      - task: account-service
      - task: account-opening-service
      - task: transaction-service
      - task: transfer-service
      - task: prompt-eval-service
      - task: chatbot-service
      - task: budget-service
      - task: ai-service
      - task: event-processor
      - task: ui-app

  user-service:
    desc: Build user-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image user-service:{{.DOCKER_TAG}} -f ./src/user-service/Dockerfile .

  account-service:
    desc: Build account-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image account-service:{{.DOCKER_TAG}} -f ./src/account-service/Dockerfile .

  account-opening-service:
    desc: Build account-opening-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image account-opening-service:{{.DOCKER_TAG}} ./src/account-opening-service/

  transaction-service:
    desc: Build transaction-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image transaction-service:{{.DOCKER_TAG}} -f ./src/transaction-service/Dockerfile .

  transfer-service:
    desc: Build transfer-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image transfer-service:{{.DOCKER_TAG}} -f ./src/transfer-service/Dockerfile .

  prompt-eval-service:
    desc: Build prompt-eval-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image prompt-eval-service:{{.DOCKER_TAG}} -f ./src/prompt-eval-service/Dockerfile .

  chatbot-service:
    desc: Build chatbot-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image chatbot-service:{{.DOCKER_TAG}} ./src/chatbot-service/

  budget-service:
    desc: Build budget-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image budget-service:{{.DOCKER_TAG}} ./src/budget-service/

  ai-service:
    desc: Build ai-service container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image ai-service:{{.DOCKER_TAG}} ./src/ai-service/

  event-processor:
    desc: Build event-processor container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image event-processor:{{.DOCKER_TAG}} ./src/event-processor/

  ui-app:
    desc: Build ui-app container image
    dir: '{{.ROOT_DIR}}'
    cmds:
      - az acr build --registry {{.ACR_NAME}} --image ui-app:{{.DOCKER_TAG}} ./src/ui-app/
