apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-demo-config
  namespace: banking-demo
data:
  USER_SERVICE_URL: "http://user-service.banking-demo.svc.cluster.local"
  ACCOUNT_SERVICE_URL: "http://account-service.banking-demo.svc.cluster.local"
  TRANSACTION_SERVICE_URL: "http://transaction-service.banking-demo.svc.cluster.local"
  TRANSFER_SERVICE_URL: "http://transfer-service.banking-demo.svc.cluster.local"
  ANOMALY_SERVICE_URL: "http://ai-service.banking-demo.svc.cluster.local"
  BUDGET_SERVICE_URL: "http://budget-service.banking-demo.svc.cluster.local"
  CHATBOT_SERVICE_URL: "http://chatbot-service.banking-demo.svc.cluster.local"
  EVENT_PROCESSOR_URL: "http://event-processor.banking-demo.svc.cluster.local"
  Services__AccountService: "http://account-service.banking-demo.svc.cluster.local"
  Services__TransactionService: "http://transaction-service.banking-demo.svc.cluster.local"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  CosmosDb__Endpoint: "REPLACE_WITH_COSMOS_ENDPOINT"
  CosmosDb__AccountsContainerName: "Accounts"
  AZURE_STORAGE_ACCOUNT_NAME: "REPLACE_WITH_STORAGE_ACCOUNT"
  AGENT_ID_AGENT_IDENTITY: "REPLACE_WITH_AZURE_CLIENT_ID"
  AzureAd__TenantId: "REPLACE_WITH_TENANT_ID"
  AzureAd__ClientId: "REPLACE_WITH_AZURE_CLIENT_ID"
  AzureAd__ClientCredentials__0__SourceType: "SignedAssertionFilePath"
  Kestrel__Endpoints__Http__Url: "http://[::]:5000"
