apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-demo

resources:
- namespace.yaml
- configmap.yaml
- user-service.yaml
- account-service.yaml
- transaction-service.yaml
- transfer-service.yaml
- anomaly-service.yaml
- budget-service.yaml
- chatbot-service.yaml
- event-processor.yaml
- redis.yaml
- hpa.yaml
- ingress.yaml
- ui-app.yaml
images:
- name: ghcr.io/banking-demo/account-service
  newName: wittybluejay46780acr.azurecr.io/account-service
  newTag: latest
- name: ghcr.io/banking-demo/anomaly-service
  newName: wittybluejay46780acr.azurecr.io/anomaly-service
  newTag: latest
- name: ghcr.io/banking-demo/budget-service
  newName: wittybluejay46780acr.azurecr.io/budget-service
  newTag: latest
- name: ghcr.io/banking-demo/chatbot-service
  newName: wittybluejay46780acr.azurecr.io/chatbot-service
  newTag: latest
- name: ghcr.io/banking-demo/event-processor
  newName: wittybluejay46780acr.azurecr.io/event-processor
  newTag: latest
- name: ghcr.io/banking-demo/transaction-service
  newName: wittybluejay46780acr.azurecr.io/transaction-service
  newTag: latest
- name: ghcr.io/banking-demo/transfer-service
  newName: wittybluejay46780acr.azurecr.io/transfer-service
  newTag: latest
- name: ghcr.io/banking-demo/ui-app
  newName: wittybluejay46780acr.azurecr.io/ui-app
  newTag: latest
- name: ghcr.io/banking-demo/user-service
  newName: wittybluejay46780acr.azurecr.io/user-service
  newTag: latest
