apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - user-service.yaml
  - account-service.yaml
  - transaction-service.yaml
  - transfer-service.yaml
  - anomaly-service.yaml
  - budget-service.yaml
  - chatbot-service.yaml
  - event-processor.yaml
  - redis.yaml
  - hpa.yaml
  - ingress.yaml
