apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: banking-demo



resources:
- namespace.yaml
- configmap.yaml
- secret-provider-class.yaml
- user-service.yaml
- account-service.yaml
- transaction-service.yaml
- transfer-service.yaml
- ai-service.yaml
- account-opening-service.yaml
- budget-service.yaml
- chatbot-service.yaml
- event-processor.yaml
- ui-app.yaml
- prompt-eval-service.yaml
images:
- name: ghcr.io/banking-demo/account-opening-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/account-opening-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/account-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/account-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/ai-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/ai-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/budget-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/budget-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/chatbot-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/chatbot-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/event-processor
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/event-processor
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/prompt-eval-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/prompt-eval-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/transaction-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/transaction-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/transfer-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/transfer-service
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/ui-app
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/ui-app
  newTag: REPLACE_WITH_TAG
- name: ghcr.io/banking-demo/user-service
  newName: REPLACE_WITH_ACR_LOGIN_SERVER/user-service
  newTag: REPLACE_WITH_TAG
