"""The golden artifact: ONE JSON file of REAL backend-emitted approval envelopes.

Cross-language drift is the recurring defect of this epic — the envelope has been stated three
times (the design doc, the shipped TypeScript + demo fixture, and this service) and the recorded
demo only ever proved the fixture against itself, never the service. This test freezes what the
service ACTUALLY emits into ``tests/fixtures/copilot-wire-envelopes.json`` (repo root), so both
sides read one file instead of agreeing with themselves:

  * this Python test asserts the service emits exactly this wire shape, and
  * a UI test (Linus) feeds the SAME file through the single mapper ``authorityWire.toApproval``
    and the real reducer, asserting the approval lands in the store with BOTH assessments and
    with rendered, material payload rows.

The file is generated by driving the REAL planner + fan-out engine (the default
``deterministic_decider`` is replaced here by a fixed dissenting decider so the golden captures the
demo's peak: a genuine primary/supervisor disagreement). Only the volatile envelope fields (`id`,
`ts`) are stripped; everything the UI consumes is preserved verbatim.

Regenerate intentionally with ``COPILOT_REGEN_GOLDEN=1 pytest tests/test_golden_wire_envelopes.py``.
A missing golden file THROWS (it is never skipped) — a golden nobody has run is not a contract.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import pytest

from app.events.bus import InMemoryTraceSink, RunStreamRegistry
from app.planner.fanout import FanOutEngine, SecondOpinion, SupervisorInput
from app.planner.limits import FanoutLimits
from app.planner.loop import Planner, PlannerRequest

GOLDEN_PATH = Path(__file__).resolve().parents[3] / "tests" / "fixtures" / "copilot-wire-envelopes.json"

LIMITS = FanoutLimits(
    max_concurrent_subagents=4,
    max_subagent_depth=2,
    per_subagent_tool_budget=20,
    subagent_wall_clock_seconds=60,
)

# A realistic authority-service response body (WireApproval, camelCase). This is the shape the
# .NET authority-service serialises; the banker-copilot-service passes it through, enriching only
# the primary's assessment with a renderable verdict and nesting the supervisor's opinion.
REALISTIC_BODY: dict[str, Any] = {
    "id": "apr_7f3c",
    "status": "pending",
    "actionId": "transaction.hold.place",
    "actionLabel": "Place hold on funds",
    "requesterId": "usr_banker_44",
    "requesterUsername": "banker@example.com",
    "sessionId": "sess_demo",
    "payload": {
        "amount": 24500,
        "fromAccountId": "acc_1187",
        "toAccountId": "acc_9920",
        "effectiveDate": "2026-05-12",
        "reason": "AML-14 structuring review",
    },
    "evidence": {
        "ev_1": {"kind": "tool_result", "label": "Three wires to one counterparty in 48h", "toolCallId": "tc_2"},
        "ev_3": {"kind": "policy", "label": "AML-14 structuring threshold", "toolCallId": "tc_4"},
    },
    "agentAssessment": {"summary": "Aggregate sits above the AML-14 trigger.", "recommendation": "proceed",
                        "evidenceToolIds": ["ev_1", "ev_3"]},
    "payloadHash": "sha256:9f2c4a7b1e8d3f60a5c2b9e4d7f1a8c3b6e9d2f5a8c1b4e7d0f3a6c9b2e5d8f1",
    "payloadHashShort": "9f2c4a7b",
    "policyVersion": "policy-2026.05.1",
    "policyId": "pol_hold_funds",
    "baseRung": "L1",
    "requiredRung": "L2",
    "requiredSigners": 2,
    "signaturesCollected": 0,
    "firedEscalators": [
        {"key": "aml.structuring", "raisedTo": "L2", "reason": "aggregate above AML-14 threshold"}
    ],
    "signatureSlots": [
        {"ordinal": 0, "minSeniority": 1, "mustDifferFrom": [], "filled": False},
        {"ordinal": 1, "minSeniority": 2, "mustDifferFrom": ["usr_banker_44"], "filled": False},
    ],
    "createdAt": "2026-05-12T14:00:00Z",
    "expiresAt": "2026-05-12T14:15:00Z",
    "executionState": "not_started",
    "callerMaySign": True,
}


class _FakeResult:
    def __init__(self, data: Any) -> None:
        self.data = data
        self.duration_ms = 1

    def summary(self) -> str:
        return "ok"


class _FakeTool:
    def __init__(self, tool_id: str, params: tuple[str, ...]) -> None:
        self.tool_id = tool_id
        self.parameters = {"properties": {p: {"type": "string"} for p in params}}


class _FakeRegistry:
    def __init__(self, tools: dict[str, _FakeTool]) -> None:
        self._tools = tools

    @property
    def tool_ids(self):
        return frozenset(self._tools)

    def get(self, tool_id: str):
        return self._tools.get(tool_id)


class _Executor:
    def __init__(self) -> None:
        self.calls: list[Any] = []

    async def invoke(self, tool_id: str, arguments: dict[str, Any], bearer: str) -> _FakeResult:
        self.calls.append((tool_id, dict(arguments)))
        return _FakeResult({"beneficiary": "Northgate Freight Ltd"})


class _Outcome:
    def __init__(self) -> None:
        self.status_code = 201
        self.body = json.loads(json.dumps(REALISTIC_BODY))

    @property
    def admitted(self) -> bool:
        return True


class _Authority:
    async def policy_catalogue(self, bearer_token: str):
        return {"actions": [{"id": "transaction.hold.place", "requiredEvidence": ["get_flagged_transaction"]}]}

    async def propose(self, body, *, bearer_token, session_id, agent_id, correlation_id):
        return _Outcome()


class _Store:
    async def save_artifact(self, artifact):
        return None


class _Session:
    def __init__(self) -> None:
        self.id = "sess_demo"
        self.context: dict[str, Any] = {}
        self.actor_id = "usr_banker_44"
        self.actor_username = "banker@example.com"


def _dissenting(spawn: SupervisorInput, own_evidence) -> SecondOpinion:
    """The demo's peak: the supervisor independently reaches the OPPOSITE verdict."""
    return SecondOpinion(
        recommendation="hold",
        confidence=0.62,
        key_factors=("counterparty is an established freight vendor", "pattern matches invoice settlement"),
        strongest_counter_argument="The customer runs a haulage business; this reads as vendor settlement, not structuring.",
    )


async def _emit_envelopes() -> list[dict[str, Any]]:
    tools = {"get_flagged_transaction": _FakeTool("get_flagged_transaction", ("transactionId",))}
    registry = _FakeRegistry(tools)
    executor = _Executor()
    runs = RunStreamRegistry(InMemoryTraceSink(), replay_window=500)
    fanout = FanOutEngine(registry=registry, executor=executor, runs=runs, limits=LIMITS, decider=_dissenting)
    planner = Planner(
        registry=registry, executor=executor, authority=_Authority(),
        max_iterations=12, store=_Store(), fanout=fanout,
    )
    req = PlannerRequest(
        session=_Session(),
        run_id="run_demo",
        objective="Review the flagged wires on account acc_1187 and place a hold pending AML-14.",
        action_id="transaction.hold.place",
        payload={"amount": 24500, "fromAccountId": "acc_1187", "toAccountId": "acc_9920"},
        facts={"amount": 24500},
        bearer_token="******",
    )
    stream = runs.create("run_demo", "sess_demo")
    await planner.run(req, stream)

    frames = runs.sink._frames.get("run_demo", [])  # type: ignore[attr-defined]
    wanted = {"approval.required", "approval.updated"}
    # Strip volatile envelope fields; keep everything the UI consumes.
    return [
        {k: v for k, v in f.items() if k not in ("id", "ts")}
        for f in frames
        if f["kind"] in wanted
    ]


@pytest.mark.asyncio
async def test_backend_emits_the_golden_wire_envelopes():
    envelopes = await _emit_envelopes()

    if os.environ.get("COPILOT_REGEN_GOLDEN"):
        GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN_PATH.write_text(json.dumps(envelopes, indent=2) + "\n")

    # A missing golden THROWS — a contract nobody has run is not a contract (epic lesson).
    golden = json.loads(GOLDEN_PATH.read_text())

    assert envelopes == golden, (
        "backend-emitted envelopes drifted from the committed golden at "
        f"{GOLDEN_PATH}. If this change is intentional, regenerate with "
        "COPILOT_REGEN_GOLDEN=1 and have Linus re-run the UI reducer test against it."
    )

    # Anti-vacuous: the golden really is the two approval envelopes, in order, carrying both
    # assessments and a genuine disagreement — not an empty list that trivially matches.
    kinds = [e["kind"] for e in golden]
    assert kinds == ["approval.required", "approval.updated"], kinds
    updated = golden[1]["payload"]["approval"]["agentAssessment"]
    # The verdict tokens are the server's OWN vocabulary, uppercased for the caption — not a
    # translation. The previous pair ("APPROVE"/"DECLINE") froze a mapping that rendered
    # `hold` as a refusal and `decline` as the mildest word on the screen.
    assert updated["primary"]["verdict"] == "PROCEED"
    assert updated["supervisor"]["verdict"] == "HOLD"
